# Generated by Django 3.2.18 on 2023-04-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20230414_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='ammount',
            new_name='amount',
        ),
    ]
