# Generated by Django 3.2.18 on 2023-04-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_rename_products_enrollment_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
