# Generated by Django 3.2.18 on 2023-04-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
