# Generated by Django 3.2.18 on 2023-04-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
