# Generated by Django 3.2.18 on 2023-05-22 10:48

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food/images/', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#00ff00', image_field=None, max_length=18, samples=None),
        ),
    ]
